CREATE TABLE IF NOT EXISTS t_requirement (
 id INTEGER PRIMARY KEY,
 code TEXT NOT NULL UNIQUE ON CONFLICT FAIL,
 name TEXT,
 descr TEXT,
 parent INTEGER  DEFAULT NULL,
 CONSTRAINT fk_parent FOREIGN KEY (parent) REFERENCES t_requirement(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS t_function (
id INTEGER PRIMARY KEY,
code TEXT NOT NULL UNIQUE ON CONFLICT FAIL,
name TEXT,
descr TEXT,
parent INTEGER DEFAULT NULL REFERENCES t_function(id) ON DELETE CASCADE,
product INTEGER DEFAULT NULL REFERENCES t_product(id) ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS t_product (
id INTEGER PRIMARY KEY,
code TEXT NOT NULL UNIQUE ON CONFLICT FAIL,
name TEXT,
descr TEXT,
parent INTEGER DEFAULT NULL REFERENCES t_product(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS t_fct_req_bind (
id INTEGER PRIMARY KEY,
id_req INTEGER NOT NULL REFERENCES t_requirement(id) ON UPDATE CASCADE ON DELETE CASCADE,
id_fct INTEGER NOT NULL REFERENCES t_function(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS t_constraint (
id INTEGER PRIMARY KEY,
code TEXT NOT NULL UNIQUE ON CONFLICT FAIL,
name TEXT,
descr TEXT
);

CREATE TABLE IF NOT EXISTS t_cstr_prod (
id INTEGER PRIMARY KEY,
id_prod INTEGER NOT NULL REFERENCES t_product(id) ON UPDATE CASCADE ON DELETE CASCADE,
id_cstr INTEGER NOT NULL REFERENCES t_constraint(id) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT cstr_no_duplicate UNIQUE (id_prod, id_cstr) ON CONFLICT IGNORE
);